OUTPUT=-o dkill.exe
WARNINGS=-Wall -Wextra
SOURCES=*.c
OPTIONS=-mwindows
DEFINES=-D_debug

all:
	$(CC) $(SOURCES) $(WARNINGS) $(OPTIONS) $(DEFINES) $(OUTPUT)

clean:
	$(RM) -f -vv *.o *.exe
